In [ ]:
import numpy as np


## 创建数组

### * 创建一组空数组 内容为随机值(未初始化)

In [28]:
l = [3,2]
x = np.empty(l, dtype= int)
print(x)


[[-1802381424         477]
 [          0           0]
 [          1  1819242542]]


### * 创建一组填充为0的数组

In [39]:
x = np.zeros(5)
print(x)
x = np.zeros((2,2) , dtype= np.float16)
print(x)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


### * 创建一组填充为1的数组

In [42]:
x = np.ones(5) # 默认为浮点数
print(x)

[1. 1. 1. 1. 1.]


## 从已有的数组创建数组

### * 列表转化

In [44]:
x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [72]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)
print()
print (a[...,1])   # 第2列元素
print (a[1,...])   # 第2行元素
print (a[...,1:])  # 第2列及剩下的所有元素

[[1 2 3]
 [3 4 5]
 [4 5 6]]

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [79]:
x = np.array([[1,2,3], [4,5,6],[7,8,9]]) 
b = a[1:3, 1:3]
c = a[1:3,[1,2]]
d = a[...,1:]
print(x)
print()
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[4 5]
 [5 6]]
[[4 5]
 [5 6]]
[[2 3]
 [4 5]
 [5 6]]


In [84]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print (x)
print ()
# 现在我们会打印出大于 5 的元素  
print (x[x >= 5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[ 5  6  7  8  9 10 11]


In [87]:
x=np.arange(32).reshape((8,4))
print(x)
print()
print (x[[4,2,1,7]])
print()
print (x[np.ix_([1,5,7,2],[0,3,1,2])])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
